apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-redis
  labels:
    app: k8s-app-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app-redis
  template:
    metadata:
      labels:
        app: k8s-app-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: k8s-app-redis