apiVersion: v1
kind: Service
metadata:
  name: k8s-app-redis
spec:
  type: ClusterIP
  ports:
   - name: k8s-app-redis
     protocol: "TCP"
     port: 6379
     targetPort: 6379
  selector:
    app: k8s-app-redis