apiVersion: v1
kind: Service
metadata:
  name: go-webapp-redis
spec:
  type: ClusterIP
  ports:
   - name: go-webapp-redis
     protocol: "TCP"
     port: 6379
     targetPort: 6379
  selector:
    app: go-webapp-redis