database:
  dialect: postgres
  host: k8s-app-postgres
  port: 5432
  dbname: testdb
  username: testusr
  password: testusr
  migration: false

redis:
  enabled: true
  connection_pool_size: 10
  host: k8s-app-redis
  port: 6379

extension:
  master_generator: false
  cors_enabled: false
  security_enabled: true

staticcontents:
  path: ./public/

log:
  request_log_format: ${remote_ip} ${account_name} ${uri} ${method} ${status}

security:
  auth_path:
    - /api/.*
  exclude_path:
    - /api/auth/login$
    - /api/auth/logout$
    - /api/health$
  user_path:
    - /api/.*
    - /release_name/.*
  admin_path:
    - /api/.*