apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: go-webapp-autoscaler

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-webapp-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75