apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-deployment
  labels:
    app: k8s-app
    k8s-app: ingress-nginx
    name: k8s-app-deployment
spec:
  replicas: {{ .Values.global.autoscaling.minReplicas }}
  selector:
    matchLabels:
      k8s-app: ingress-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%

  template:
    metadata:
      labels:
        k8s-app: ingress-nginx
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: k8s-app
          image: {{ .Values.global.dockerParameter.dockerPath }}:{{ .Values.global.dockerParameter.dockerVersion }}
          imagePullPolicy: Always
          securityContext:
            privileged: True
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{ (index .Values.resources "default") | toJson }}
          env:
            - name: WEB_APP_ENV
              value: "k8s"
            - name: CONFIGURE_DATABASE_HOST
              value: "go-webapp-postgres"
            - name: CONFIGURE_DATABASE_PORT
              value: "5432"
            - name: CONFIGURE_DATABASE_DBNAME
              value: "testdb"
            - name: CONFIGURE_DATABASE_USERNAME
              value: "testusr"
            - name: CONFIGURE_DATABASE_PASSWORD
              value: "testusr"
            - name: CONFIGURE_REDIS_ENABLED
              value: "true"
            - name: CONFIGURE_REDIS_HOST
              value: "go-webapp-redis"
            - name: CONFIGURE_REDIS_PORT
              value: "6379"
            - name: CONFIGURE_REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: "/api/health"
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: "/api/health"
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 3