apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name:  k8s-app-access-nginx
spec:
  podSelector:
    matchLabels:
      k8s-app: ingress-nginx
  ingress:
  - from:
    - podSelector:
        matchLabels: #mutable fields
          k8s-app: ingress-nginx
