apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name:  go-webapp-access-nginx
spec:
  podSelector:
    matchLabels:
      app: k8s-app
  ingress:
  - from:
    - podSelector:
        matchLabels: #mutable fields
          app.kubernetes.io/name: ingress-nginx
