apiVersion: v1
kind: Service
metadata:
  name: go-webapp

spec:
  selector:
    app: go-webapp
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      targetPort: 8080
      port: 80
      nodePort: 30000
