apiVersion: v1
kind: Service
metadata:
  name: go-webapp

spec:
  selector:
    app: go-webapp
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

