apiVersion: v1
kind: Service
metadata:
  name: k8s-app-postgres
spec:
  selector:
    app: k8s-app-postgres
  type: ClusterIP
  clusterIP: None
  ports:
   - name: "db-port"
     protocol: "TCP"
     port: 5432
     targetPort: 5432
